### PR TITLE
Implement tokenization errors as per spec.

### PR DESCRIPTION
**Pull request by inikulin**
Ready for a review, but it makes sense to merge spec changes first. Note that for now we've decided to move new error codes to a separate section in tree construction stage tests to not mix things up. Once we have a spec for tree construction stage errors, we'll remove old errors and move new errors to `#errors` section.

Spec PR: https://github.com/whatwg/html/pull/2701

### CODE REVIEW

**Comment by inikulin** [comment]
Spec PR has been merged. This one is ready for review.

**Comment by inikulin** [comment]
Ping @gsnedders

**Comment by inikulin** [comment]
@gsnedders 

> Apart from the one issue, what's going on with the tree construction tests? Some of the #errors sections have been partially updated for the tokenizer errors, in addition to the #new-errors sections? 

Unfortunately, seems like some error codes were erroneously added to the legacy error section and we missed it on review. I'll do a cleanup. 

> Personally, I have a slight preference against adding a new section temporarily, given I know some things rely on the specific headings

I thought it would be an unobtrusive way for a transition to the new parse errors. The other options are:
- Remove all old parse errors in the tree construction tests and add new ones directly to the `#errors` section. But there can be implementations that use old parse errors.
- Move all new error in the `#errors` section, but use separator between old and new parse errors (e.g., `(0,0) -------`). Will not work due to the same reasons as the previous option. 

Do you have any other ideas?

**Comment by gsnedders** [comment]
@inikulin 

> Do you have any other ideas?

Not really. :) Adding a new section probably makes as much sense as anything else.

**Comment by inikulin** [comment]
@gsnedders Fixed

**Pull request merged**
