### PR TITLE
Add test for `</button>` closing `<p>`

### LINKED ISSUE #143: Missing coverage for `<button><p></button>x`
`button` is special in relation to `p` (in that `</button>` generates implied end tags),
...
I don't see a test for `<button><p></button>x`, so that is missing coverage.

_Originally posted by @zcorpan in https://github.com/html5lib/html5lib-tests/issues/142#issuecomment-1035690952_

> An end tag whose tag name is one of: "address", "article", "aside", "blockquote", "button", "center", "details", "dialog", "dir", "div", "dl", "fieldset", "figcaption", "figure", "footer", "header", "hgroup", "listing", "main", "menu", "nav", "ol", "pre", "section", "summary", "ul"

https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody

### PR DESCRIPTION
**Pull request by fb55**
Fixes #143

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]

**Comment by stevecheckoway** [comment]
I don't believe `<!doctype html><button><p></button>x` has any errors and thus, I think the added test is incorrect.

My read of the standard is
1. The parser starts in the "initial" insertion mode and reads a DOCTYPE token whose name is html. This switches to "before html";
2. In the "before html" insertion mode, the `<button>` token is handled by "Anything else" which switches to "before head";
3. In the "before head" insertion mode, the `<button>` token is handled by "Anything else" which switches to "in head";
4. In the "in head" insertion mode, the `<button>` token is handled by "Anything else" which switches to "after head";
5. In the "after head" insertion mode, the `<button>` token is handled by "Anything else" which switches to "in body";
6. In the "in body" insertion mode, the `<button>` token is handled by "A start tag whose tag name is 'button'" which causes no errors because there is not a button element in scope;
7. In the "in body" insertion mode, the `<p>` token is handled by "A start tag whose tag name is one of: … 'p'…";
8. In the "in body" insertion mode, the `</button>` token is handled by "An end tag whose tag name is one of: … 'button' …" which generates implied end tags—this pops the `p` element off the stack of open elements—leaving the `button` element as the current node and thus not causing an error;
9. In the "in body" insertion mode, the `x` token is handled by "Any other character token"; and
10. In the "in body" insertion mode, the end-of-file token is handled by "An end-of-file token" which does not cause an error because the stack of open elements only contains `html` and `body` and the parsing ends here.

Was this a copy and paste error or have I missed something in the standard that causes these three errors?

**Comment by alexander-akait** [comment]
@stevecheckoway Yes, you are right, there are no errors in this test case

**Comment by fb55** [comment]
Yeah, this was an oversight on my part. Sorry for that!

**Comment by flavorjones** [comment]
@alexander-akait @fb55 Do you think it's possible to merge @stevecheckoway's PR at #149 if his analysis is correct?

**Comment by alexander-akait** [comment]
@flavorjones Sorry, I don't have permissions to merge :disappointed:

**Comment by fb55** [comment]
I don't have permissions either. @Ms2ger how do you feel about adding additional collaborators to this repo?

**Comment by Ms2ger** [comment]
I don't have permissions to add anyone else, maybe @jgraham?

**Pull request merged**
