### PR TITLE
Test U+0000 in bogus comment and bogus doctype states

### PR DESCRIPTION
**Pull request by zcorpan**
Follows https://github.com/whatwg/html/pull/2939

---

Note: I included literal U+0000 and U+FFFD here, not sure if that should be done differently? Also I haven't yet tested this against an implementation, just putting this up for review. Maybe @inikulin wants to implement and run the tests?

### CODE REVIEW

**Comment by inikulin** [comment]
Tests with such literals usually go to https://github.com/html5lib/html5lib-tests/blob/master/tree-construction/domjs-unsafe.dat. Also, it's more preferable to have tokeniser tests for this one rather than tree construction: implementations that doesn't implement tree construction stage will be able to use these tests and you can escape problematic literals in tokeniser tests.

> Maybe @inikulin wants to implement and run the tests?

I'll do once we have nits above fixed.

**Comment by zcorpan** [comment]
Thanks, PTAL

**Comment by inikulin** [comment]
@zcorpan Thank you! Will try to implement it within next few days.

**Comment by zcorpan** [comment]
Thank you!

**Pull request merged**
